package Vista;


import Controlador.PplRepar;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sala319
 */
public class FrmReparto extends javax.swing.JFrame {
private FrmReenviar vtnValidar;
    

    public FrmReparto(java.awt.Frame parent, boolean modal) {
        setLocationRelativeTo(this);
              initComponents();
              asignarFecha();
              this.jTextRadicado.setEnabled(false);
              this.jDateChooser1.setEnabled(false);
         }

   
//              this.jDateChooser2.setEnabled(false);
              
         
  

    

    
       
          private void asignarFecha(){
            Calendar fecha = new GregorianCalendar();
            
            String hoy = "";
            System.out.println(fecha.get(Calendar.MONTH));
            int año = fecha.get(Calendar.YEAR);
            int mes = fecha.get(Calendar.MONTH)+1;
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
            int hora = fecha.get(Calendar.HOUR_OF_DAY);
            int minuto = fecha.get(Calendar.MINUTE);
            int segundo = fecha.get(Calendar.SECOND);
            hoy = dia+"/"+mes+"/"+año+" "+hora+":"+minuto+":"+segundo; 
            
//             JOptionPane.showMessageDialog(rootPane, hoy);
             
             try{   
                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                    Date fechaDate = new Date();
                    fechaDate = formato.parse(hoy);              
                    
                                                          
                    this.jDateChooser1.setDate(fechaDate);
                    jDateChooser1.getDateEditor().setEnabled(false);
               
                   
                    
                 
             }catch (ParseException ex){
             Logger.getLogger(FrmReparto.class.getName()).log(Level.SEVERE,null, ex);
         }
         } 
        

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextRadicado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextObservacion = new javax.swing.JTextPane();
        jBtnAñadir = new javax.swing.JButton();
        Mensaje = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtDocumento = new javax.swing.JTextField();
        jEst_Repar = new javax.swing.JComboBox();
        jBtnReenviar = new javax.swing.JButton();
        jComboBoxResp = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTxtDocuReen = new javax.swing.JTextField();
        jBtnNuevoRadicado = new javax.swing.JButton();
        JBCAgregar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reparto");

        jLabel1.setText("Numero Radicado:");

        jTextRadicado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextRadicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRadicadoActionPerformed(evt);
            }
        });
        jTextRadicado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextRadicadoFocusGained(evt);
            }
        });
        jTextRadicado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextRadicadoKeyTyped(evt);
            }
        });

        jLabel2.setText("Fecha:");

        jLabel4.setText("Estado Reparto:");

        jLabel5.setText("Respuesta:");

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero Radicado ", "Reparto", "Respuesta", "Observacion", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(TablaDatos);

        jLabel7.setText("Observacion:");

        jScrollPane3.setViewportView(jTextObservacion);

        jBtnAñadir.setText("AÑADIR");
        jBtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAñadirActionPerformed(evt);
            }
        });

        Mensaje.setForeground(new java.awt.Color(0, 153, 153));

        jLabel8.setText("Documento:");

        jTxtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDocumentoActionPerformed(evt);
            }
        });

        jEst_Repar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar:", "Activo", "no Activo" }));

        jBtnReenviar.setText("Reenviar Correspondencia");
        jBtnReenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnReenviarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnReenviarMouseReleased(evt);
            }
        });
        jBtnReenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReenviarActionPerformed(evt);
            }
        });

        jComboBoxResp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar:", "Si", "No" }));

        jLabel9.setText("Documentos Reenviados");

        jTxtDocuReen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDocuReenActionPerformed(evt);
            }
        });

        jBtnNuevoRadicado.setText("Nuevo Radicado");

        JBCAgregar.setText("Agregar Reparto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addContainerGap(617, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jBtnAñadir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxResp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTxtDocumento)
                                                    .addComponent(jTextRadicado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jEst_Repar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(47, 47, 47))))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtDocuReen, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnNuevoRadicado)
                        .addGap(35, 35, 35)
                        .addComponent(JBCAgregar)
                        .addGap(32, 32, 32)
                        .addComponent(jBtnReenviar)
                        .addGap(69, 69, 69)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextRadicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jEst_Repar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTxtDocuReen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReenviar)
                    .addComponent(jBtnAñadir)
                    .addComponent(jBtnNuevoRadicado)
                    .addComponent(JBCAgregar))
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextRadicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRadicadoActionPerformed
     
    }//GEN-LAST:event_jTextRadicadoActionPerformed

    private void jTextRadicadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRadicadoKeyTyped
       char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9') evt.consume(); 
        
        String cadena = jTextRadicado.getText();
        if(cadena.length() >=10000000)evt.consume();
        
  
    }//GEN-LAST:event_jTextRadicadoKeyTyped

    private void jTextRadicadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRadicadoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRadicadoFocusGained

    private void jBtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAñadirActionPerformed
        // TODO add your handling code here:
//        Mensaje.setText("");
//        DefaultTableModel model=(DefaultTableModel) TablaDatos.getModel();
//        if(!jTextRadicado.getText().trim().equals("")) {
//            model.addRow(new Object[]{jTextRadicado.getText(),jEst_Repar.getSelectedItem(),
//                jComboBoxResp.getSelectedItem(),jTextObservacion.getText(),jDateChooserFecha.getCalendar()});
//        
//        }else{
//            Mensaje.setText("El Numero del radicado no se debe dejar en blaco");
//        }
    }//GEN-LAST:event_jBtnAñadirActionPerformed

    private void jTxtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDocumentoActionPerformed

    private void jBtnReenviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReenviarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnReenviarMousePressed

    private void jBtnReenviarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReenviarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnReenviarMouseReleased

    private void jBtnReenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReenviarActionPerformed
    
      PplRepar vtnValidar = new PplRepar();
   //     vtnValidar.iniciar();    
        
        
    }//GEN-LAST:event_jBtnReenviarActionPerformed

    private void jTxtDocuReenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDocuReenActionPerformed
if( jTxtDocuReen.getText().equals("")){
 
    
    JOptionPane.showMessageDialog(null, "Campo Obligatorio");
 
    }else{
 
}        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDocuReenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReparto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReparto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReparto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReparto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmReparto dialog = new FrmReparto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBCAgregar;
    private javax.swing.JLabel Mensaje;
    public javax.swing.JTable TablaDatos;
    public javax.swing.JButton jBtnAñadir;
    public javax.swing.JButton jBtnNuevoRadicado;
    public javax.swing.JButton jBtnReenviar;
    public javax.swing.JComboBox jComboBoxResp;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JComboBox jEst_Repar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextPane jTextObservacion;
    public javax.swing.JTextField jTextRadicado;
    public javax.swing.JTextField jTxtDocuReen;
    public javax.swing.JTextField jTxtDocumento;
    // End of variables declaration//GEN-END:variables

 
}
